server:
  port: ${SERVER_PORT:8080}
  servlet:
    encoding:
      charset: UTF-8

spring:
  application:
    name: eproject
  thymeleaf:
    cache: false
  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update # ou validate/none, dependendo do seu cenário
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:sqlserver://sqlserver-escolar.database.windows.net:1433;databaseName=db-sistema-escolar;encrypt=true;trustServerCertificate=false;loginTimeout=30;
    username: ${DB_USERNAME:admsql}   # Use variáveis de ambiente
    password: ${DB_PASSWORD:Fiap@2tdsvms}  # Use variáveis de ambiente
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

logging:
  level:
    root: INFO
    br: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
